### ISSUE TITLE
哎呦

### ISSUE THREAD

**Issue by wangzhnxin** [litcc/net-speeder#1]
这是你写的吗？复制的也要著名下作者啊。

**Comment by litcc** [comment]
？？我复制哪的？

2016-08-19 16:45 GMT+08:00 zenshin <notifications@github.com>:

**Comment by wangzhnxin** [comment]
@litcc 网上搜出来的都比你这个早，你这只是脚本里换了个中文提示，中文在没有设置语言的环境中是乱码。
